---
#
- name: create kibana group
  group: name=kibana state=present

- name: create kibana user
  user: name=kibana group=kibana

- name: install required packages
  yum: name={{ item }} state=present
  with_items:
    - curl
    - tar
    - ca-certificates

- name: prepare kibana home
  file:
    path: "{{ kibana_home }}"
    state: directory
    owner: "kibana"
    group: "kibana"

- name: download kibana
  get_url:
    url: "https://download.elastic.co/kibana/kibana/kibana-{{ kibana_version }}-linux-x64.tar.gz"
    dest: /tmp/kibana-{{ kibana_version }}.tar.gz
    #checksum: 66dffb5228a211e61d6d7ef4a86f5758

- unarchive: src=/tmp/kibana.tar.gz dest={{ kibana_home }} owner=kibana group=kibana
