---
#
- name: create kibana group
  group: name=kibana state=present

- name: create kibana user
  user: name=kibana group=kibana

- name: install required packages
  yum: name={{ item }} state=present
  with_items:
    - curl
    - tar
    - ca-certificates

- name: prepare kibana home
  file:
    path: "{{ kibana_home }}"
    state: directory
    owner: "kibana"

- set_fact:
    kibana_filename: kibana-{{ kibana_version }}-linux-x64

- unarchive:
    src: "https://download.elastic.co/kibana/kibana/{{ kibana_filename }}.tar.gz"
    dest: "/tmp"
    copy: no
    creates: /tmp/{{ kibana_filename }}

- command: mv /tmp/{{ kibana_filename }}/ /opt/kibana
